USER_24_PUBLIC__22hellotest3_22:
  target: dev
  outputs:
    dev:
      type: snowflake
      role: SYSADMIN
      warehouse: MYTESTWH1_HIDAKA
      database: DB_KUBO
      schema: PUBLIC
      account: ' '
      user: ' '
