name: Hello World Workflow

on:
  push:
    branches: [ "main" ]
 
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Say Hello
        run: echo "Hello, GitHub Actions! 🚀"

  hoge:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Hoge Step
        run: echo "Hoge, GitHub Actions! 🚀"
